version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/common"
    schedule:
      interval: "daily"
  - package-ecosystem: "composer"
    directory: "/composer/helpers/v1"
    schedule:
      interval: "daily"
  - package-ecosystem: "composer"
    directory: "/composer/helpers/v2"
    schedule:
      interval: "daily"
  - package-ecosystem: "mix"
    directory: "/hex/helpers"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/npm_and_yarn/helpers"
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "/python/helpers"
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    directory: "/go_modules/helpers"
    schedule:
      interval: "daily"
